### PR TITLE
Correct message handling in various exception raises

### PR DESCRIPTION
**Pull request by tithomas1**
Some exception raises were passing the message as the first positional instead of by name. That would of caused the message to be interpreted as an error_code

### CODE REVIEW

**Comment by tithomas1** [comment]
Additionally, maybe more controversial, is the lack of exception handling around the YdkGenerate calls in generate.py. A traceback can occur (a missing module dependency in the bundle for example) and there's no indication of what happened other than the call stack. Note those errors can be seen if verbose is enabled (but you still get a traceback).

**Comment by psykokwak4** [comment]
Thanks for contribution, I think this improvement should save time for both users and developers.
One quick question, why is error message printed in except block but not raised?

**Comment by abhikeshav** [comment]
Agreed. Feel free to submit a fix for this or to discuss a possible fixes

**Comment by psykokwak4** [comment]
Maybe the issue is `YdkGenException` is not using `super` constructor correctly? So under Python 2 environment it is not able to show propagated trace back(a missing module dependency in the bundle for example).

```diff
index a1a7e37..deb56d3 100644
--- i/ydkgen/common.py
+++ w/ydkgen/common.py
@@ -99,6 +99,7 @@ class YdkGenException(Exception):
     """

     def __init__(self, msg):
+        super(YdkGenException, self).__init__(msg)
         self.msg = msg
         logger = logging.getLogger('ydkgen')
         if len(logger.handlers) == 1:
```

**Comment by tithomas1** [comment]
Ah, yes, that super init call should be there and it would trigger the output of any of the accumulated error messages after the traceback. However, I think it's still a good idea to catch at least the YdkGenException in generate.py to avoid the traceback altogether. It just looks "cleaner" when run.

**Comment by psykokwak4** [comment]
Looks cleaner but not canonical way to raise error :), will leave other YDK developers to comment/merge pull request

**Comment by 111pontes** [comment]
IMHO, functions should raise exceptions.  Scripts should write error messages to stderr.

**Comment by abhikeshav** [comment]
Hi @111pontes feel free to [add your review comments](https://github.com/CiscoDevNet/ydk-gen/pull/440/files) to request any changes or approve this pull request. This may be the practice we should adopt.

**Comment by abhikeshav** [comment]
I'll go ahead and merge this. Thanks a lot for your contribution @tithomas1 ! Much appreciated 👍

**Pull request merged**
