### PR TITLE
add onbox netconf support for virtual routers such as enxr

### PR DESCRIPTION
**Pull request by traveldan88**

### CODE REVIEW

**Comment by traveldan88** [comment]
fixed one bug on reformating the netconf response, make changes to make the code conform to the python coding style required by ydk

**Comment by psykokwak4** [comment]
Thanks for contribution. 
The tests not passed in CI could be reproduced using the following steps:
1. download ConfD 1.6
2. start ConfD session
3. generate and install `ydk` and `ydk-models-ydktest` bundle
4. execute test script

Example steps:
```bash
# 1. download ConfD 1.6
$ wget https://github.com/CiscoDevNet/ydk-gen/files/562559/confd-basic-6.2.darwin.x86_64.zip
$ unzip confd-basic-6.2.darwin.x86_64.zip
$ ./confd-basic-6.2.darwin.x86_64.installer.bin ../confd
# 2. start ConfD session
$ source ../confd/confdrc
$ cd <ydk-gen>/sdk/cpp/core/tests/confd/ydktest/
$ make clean all start
# 3. generate and install ydk core/ydk-models-ydktest
...
# 4. run test
$ cd <ydk-gen>/sdk/python/core/tests/
$ python test_sanity_netconf.py
```
Seems like `NetconfService.edit_config` is returning an rpc instance, either test case or source code should be fixed, and it would be better if the changes are python2/3 compatible.

**Comment by traveldan88** [comment]
HI Xiaoqin:
   I followed the instruction of your sanity test, but I got the following error when I tried to run python test:
   bash-4.2$ python  test_sanity_netconf.py
Traceback (most recent call last):
  File "test_sanity_netconf.py", line 23, in <module>
    from compare import is_equal
  File "/nobackup/daye/ydk-new/ydk-gen/sdk/python/core/tests/compare.py", line 23, in <module>
    from ydk.types import (Empty, Decimal64, FixedBitsDict,
ImportError: No module named ydk.types
bash-4.2$ 

Is there any environment variables I need to set before I run this test because the module path is not set up correctly?

**Comment by traveldan88** [comment]
I fixed the following error by adding to the PYTHONPATH:
    ImportError: No module named ydk.types

However, I got the second error:Traceback (most recent call last):
  File "test_sanity_netconf.py", line 26, in <module>
    from ydk.models.ydktest import ydktest_sanity as ysanity
ImportError: No module named ydktest

I could not find the module ydktest from the ydk/models directory:
bash-4.2$ cd models/
bash-4.2$ ls
__init__.py  __init__.pyc

Does this module has to be downloaded separately?

**Comment by traveldan88** [comment]
I think the primary reason why I can't execute test because step3 failed on my machine:
generate and install ydk and ydk-models-ydktest bundle
bash-4.2$ make clean all start
rm -rf \
                *.o *.a *.xso *.fxs *.xsd *.ccl \
                *_proto.h \
                ./confd-cdb *.db aaa_cdb.* \
                rollback*/rollback{0..999} rollback{0..999} \
                host.key host.cert ssh-keydir \
                *.log confderr.log.* \
                etc *.access \
                running.invalid global.data _tmp*
rm -rf *_ns.py *.pyc *.yang 2> /dev/null || true
cp ../../models/ydktest-filterread\@2015-11-17.yang ydktest-filterread.yang
/nobackup/daye/ydk-test/../confd/bin/confdc --fail-on-warnings  -c -o ydktest-filterread.fxs  ydktest-filterread.yang
/nobackup/daye/ydk-test/../confd/bin/confdc: line 36: /nobackup/daye/ydk-test/../confd/lib/confd/erts/bin/confdexec: cannot execute binary file
/nobackup/daye/ydk-test/../confd/bin/confdc: line 36: /nobackup/daye/ydk-test/.: Success
make-3.81: *** [ydktest-filterread.fxs] Error 126

The confdexec can't be executed on my ads machine, thus the make all failed and failed to install ydk test pacakge. 

My ads machine is a liunx cel7 and confdexec doesn't run on the machine.

**Comment by psykokwak4** [comment]
@traveldan88 
Sorry for my late reply.
For the first and the second error. You could try it under a virtualenv:
```bash
$ cd <ydk-gen>
$ virtualenv my_env
$ source my_env/bin/activate
(my_env)$ pip install -r requirements.txt # <-- might have issue on installing lxml
(my_env)$ ./generate.py --core
(my_env)$ ./generate.py --bundle profiles/test/ydktest-cpp.json
(my_env)$ pip install gen-api/python/ydk/dist/ydk-0.5.5.tar.gz
(my_env)$ pip install gen-api/python/ydktest-bundle/dist/ydk-models-ydktest-0.1.0.tar.gz
```
Then go to the test directory and execute `test_sanity_netconf.py`:
```
(my_env)$ cd sdk/python/core/tests
(my_env)$ python test_sanity_netconf.py
```
For the ConfD error, sorry I provided you a link to OS X version(confd-basic-6.2.**darwin**.x86_64.zip), to download the linux version:
```bash
wget https://github.com/CiscoDevNet/ydk-gen/files/562538/confd-basic-6.2.linux.x86_64.zip
```
You can try to download other versions of ConfD from this [site](https://developer.cisco.com/site/confD/downloads/).

**Comment by traveldan88** [comment]
@psykokwak4 
Thanks for your answers.  Now I'm able to run sanity test on my mac (linux version doesn't work because confd doesn't have a version works on cel7 machine, all versions are linux 6.x version doesn't work on cel7).  I've found the root cause of the sanity error. I made changes based on an older version of ydk netconf code, which caused the sanity to fail. I will port my changes to the latest ydk-gen code and that shall fix the problem.

**Comment by traveldan88** [comment]
I've updated my diff based on the latest ydk-gen code and now the sanity runs ok. 

I found one important bug in current ydk-gen netconf code vs the one I used originally (which is ydk-0.5.4), the ydk-gen netconf decode breaks the get operation for real router get and cause the ydk router configuration test script I used to test my onbox code to fail. 

The bug is in class _ClientSPPlugin, member function decode:
   The correct version shall be:
   for yang_node_name in yang_nodes:

            found = False
            for member in current._meta_info().meta_info_class_members:
                if member.name == yang_node_name:
                    found = True
                    current = getattr(current, member.presentation_name)
                    if current is None:
                        return None
                    if isinstance(current, YList):
                        if len(current) == 0:
                            return None
                        if len(current) > 2:   <=== this is the correct version
                            return current
                        if len(current) == 1:  <== this is the correct version
                            current = current[0]

The incorrect code in most recent ydk-gen is 
   if isinstance(current, YList):
                        if len(current) == 0:
                            return None
                        if len(current) > 0:
                            return current

This bug caused the get operation from a real cisco router to fail because the object returns contains nothing (in case of isis test)

I fixed this problem and i think to properly test ydk, one shall use real router instead of confd because confd test doesn't find this bug which actually breaks the decode function and cause get operation to fail on real router.

**Comment by psykokwak4** [comment]
@traveldan88 
Agreed, we are running basic sanity tests against ConfD in travis CI, full-fledged test cases should be run against a real router.

**Pull request merged**
