### PR TITLE
Issue 216

### PR DESCRIPTION
**Pull request by psykokwak4**
Will only print import statements used for derived identity classes

### CODE REVIEW

**Comment by abhikeshav** [comment]
Does this work with the models attached in the issue#216 (https://github.com/CiscoDevNet/ydk-gen/files/412147/models.zip)?

**Comment by psykokwak4** [comment]
There is a generated `import_test.py` under `path/to/gen-api/ydk/tests/import_tests.py`, could be used to verify this patch. After applying this patch, there is still one error, which is related to #230.

**Comment by abhikeshav** [comment]
OK. Thanks. Feel free to assign #230 to yourself so that the attached models will work

**Comment by psykokwak4** [comment]
Ok.

**Pull request merged**
